version: "3"
services:
  db:
    image: mdillon/postgis
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    restart: always
  sync:
    image: citykleta/osm-data-sync
    depends_on:
      - db
    env_file:
      - dev.env
    environment:
      - POSTGRES_HOST=db
  mapbox:
    image: citykleta/postgis-to-mapbox
    depends_on:
    - db
    env_file:
    - dev.env
    environment:
    - POSTGRES_HOST=db
